const movies = [
    {
      id: 1,
      movieName: "Avatar: The Way of Water",
      actors: ["actor1", "actor2"],
      imageSrc: "./pictures/Avatar.jpg",
      description: "is a 2022 American epic science fiction film co-produced and directed by James Cameron, who co-wrote the screenplay with Rick Jaffa and Amanda Silver from a story the trio wrote with Josh Friedman and Shane Salerno. Distributed by 20th Century Studios, it is the sequel to Avatar (2009) and the second installment in the Avatar film series. Cast members Sam Worthington, Zoe Saldaña, Stephen Lang, Joel David Moore, CCH Pounder, Giovanni Ribisi, Dileep Rao and Matt Gerald reprise their roles from the original film, with Sigourney Weaver returning in an additional role,[6] while Kate Winslet joined the cast. It follows a blue-skinned humanoid Na'vi named Jake Sully (Worthington) as he and his family, under renewed human threat, seek refuge with the aquatic Metkayina clan of Pandora, a habitable exomoon on which they live",
      rate: 7,
      liked: 0,
      type:"advanture"
    },
    {
      id: 2,
      movieName: "Spider-Man: No Way Home",
      actors: ["actor1", "actor2"],
      imageSrc: "./pictures/Spider-Man.jpg",
      description: "some description about movie",
      liked: 0,
      rate: 7,
      type:"action"
    }, 
    {
        id: 3,
        movieName: "some name",
        actors: ["actor1", "actor2"],
        imageSrc: "url/path",
        description: "some description about movie",
      liked: 0,
      rate: 7,
      },
       {
        id: 4,
        movieName: "some name",
        actors: ["actor1", "actor2"],
        imageSrc: "url/path",
        description: "some description about movie",
      liked: 0,
      rate: 7,
      },
      {
        id: 5,
        movieName: "some name",
        actors: ["actor1", "actor2",...],
        imageSrc: "url/path",
        description: "some description about movie",
      liked: 0,
      rate: 7,
      },
       {
        id:6,
        movieName: "some name",
        actors: ["actor1", "actor2",...],
        imageSrc: "url/path",
        description: "some description about movie",
      liked: 0,
      rate: 7,
      }, 
      {
        id: 7,
        movieName: "some name",
        actors: ["actor1", "actor2",...],
        imageSrc: "url/path",
        description: "some description about movie",
      liked: 0,
      rate: 7,
      }, 
      {
        id: 8,
        movieName: "some name",
        actors: ["actor1", "actor2",...],
        imageSrc: "url/path",
        description: "some description about movie",
      liked: 0,
      rate: 7,
      },
       {
        id: 9,
        movieName: "some name",
        actors: ["actor1", "actor2",...],
        imageSrc: "url/path",
        description: "some description about movie",
      liked: 0,
      rate: 7,
      },
       {
        id: 10,
        movieName: "some name",
        actors: ["actor1", "actor2",...],
        imageSrc: "url/path",
        description: "some description about movie",
      liked: 0,
      rate: 7,
      },
  ];